default: &default
  adapter: postgresql
  encoding: unicode
  username: deployer
  port: 5432
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  host: 127.0.0.1
  database: homework_development

test:
  <<: *default
  host: 127.0.0.1
  database: homework_test

production:
  encoding: unicode
